### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by ceresti** [silentsokolov/go-vimeo#1]
- Is there a reason that the /me/videos call is not supported?  
- Is there a reason why not all of the JSON returned it put into the Video struct?

**Comment by silentsokolov** [comment]
> Is there a reason that the /me/videos call is not supported?

I put this in the documentation [here](https://godoc.org/github.com/silentsokolov/go-vimeo#UsersService.ListVideo) and [here](https://github.com/silentsokolov/go-vimeo#where-me-service). And take a look at the [code](https://github.com/silentsokolov/go-vimeo/blob/master/users.go#L536). Sorry, the description of the methods is pretty meager, but I'm working on it!
 
> Is there a reason why not all of the JSON returned it put into the Video struct?

What do you have in mind? One of the fields is missing?

**Comment by ceresti** [comment]
Thanks for responding so quickly.

My bad, I did not see the ‘Me’ documentation.

I do need access to the ‘File’ subtree of the JSON response.  I’ve just added this in the fork I created and am now testing it.  It would be great if it came directly from your version.

Mark

**Comment by silentsokolov** [comment]
Well ... i waiting commit/PR in your fork

**Comment by ceresti** [comment]
Sorry … I didn’t understand that you were waiting.  I’ll get that out today.
