### ISSUE TITLE
Upload video metadata

### ISSUE THREAD

**Issue by bjg2** [silentsokolov/go-vimeo#14]
Hi! Thanks for this lib!

Is there any way to upload video with given name / description / etc, or should I upload video first and then edit it's name / metadata / privacy later? It would be better, not to exist nor be public until all its meta is set....

**Comment by silentsokolov** [comment]
Hi!

First, you can't upload video using only one file. You need create a video object, get a video id, then use this id to upload file. Docs [here](https://developer.vimeo.com/api/upload/videos#resumable-approach).

So, 
1) Create a video object with given name / description / etc and mark as "hideen"
2) Get ID
3) Upload file using ID
4) Mark as "public"
