### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by olafdraeger** [silentsokolov/go-vimeo#3]
Sorry if this is not the right place to ask and please just delete if not applicable.
Uploading / replacing existing videos is a breeze using this library - thanks for the effort!
I'd need to also update thumbnails after replacing videos but can't find an implementation of the relevant POST anywhere. So am I right to assume that it doesn't exist?

**Comment by silentsokolov** [comment]
```go
f, _ := os.Open(filePath)
r := &vimeo.PicturesRequest{}

pics, _, _ := client.Videos.UploadPicture(videoID, r, f)
```

**Comment by olafdraeger** [comment]
thanks a lot. i was away for a couple of days but managed to do what I had tried to do just before heading out last friday. all i needed was to have a thumbnail image created and activated from a newly uploaded clip. when digging a bit into your code i found client.Videos.CreatePictures, which did exactly what i needed to do. wanted to let you know but it seems to be a bit late now. thanks for creating this!
