### ISSUE TITLE
Filtering personal videos by tag

### ISSUE THREAD

**Issue by kresic-ivan-nsoft** [silentsokolov/go-vimeo#5]
Hi there,

it's a bit hard to manage with few examples and no documentation. I'm trying to filter my personal videos by tag.

I'm trying with adVideos, _, adVideosErr := client.Users.ListVideo("", vimeo.OptFilter("tags=ad")). Any clues here?

Thanks in advance

**Comment by silentsokolov** [comment]
Hi, yea, documentation is my problem ((

But, but you can find the method by reference from the official documentation. Example:

`https://developer.vimeo.com/api/playground/tags/%7Bword%7D/videos`  -> `https://github.com/silentsokolov/go-vimeo/blob/master/vimeo/tags.go#L79`

```go
// ListVideo lists the video for an tag.
//
// Vimeo API docs: https://developer.vimeo.com/api/playground/tags/%7Bword%7D/videos
```

**Comment by kresic-ivan-nsoft** [comment]
Hi @silentsokolov,

thanks for the quick reply. I was close :)
