### ISSUE TITLE
Lists of videos produce JSON unmarshal error 

### ISSUE THREAD

**Issue by lukasschwab** [silentsokolov/go-vimeo#6]
The following code:

```go
vids, _, err := cli.Users.ListLikedVideo(uid)
if err != nil {
  println(err.Error())
}
```

Produces the follwing error:

```
json: cannot unmarshal object into Go struct field Category.parent of type string
```

This is also the case for a request for a user's videos; the following code produces an identical error:

```go
vids, _, err := cli.Users.ListVideo(uid)
if err != nil {
  println(err.Error())
}
```

+ go-vimeo v2.2.0 
+ go v1.10.2

Let me know if I can provide any additional information!
Lukas

**Comment by silentsokolov** [comment]
Thanks, fix.

Update to 2.2.1
