### ISSUE TITLE
ListVideo("", vimeo.OptQuery("videoName")) returns an empty video list

### ISSUE THREAD

**Issue by olafdraeger** [silentsokolov/go-vimeo#7]
Hi Dmitriy,

just wondering if something has changed in the 2.2.1 version with regards to the query options for the ListVideo() call?

I frequently need to replace video files of existing videos and have used the same code to do that over and over again but it now has stopped working. I haven't used it in several months but when I tried now to fetch the video object from Vimeo for the Video that I need to replace, I get an empty video list back. I triple-checked and the video I've passed to the queryOption certainly exists.
thanks,
olaf

**Comment by silentsokolov** [comment]
Hi, can you show the code? 
- Perhaps the method returns an error?
- `ListVideo()` without `OptQuery`, return videos?
- Try to repeat the request in the [sandbox](https://developer.vimeo.com/api/playground/)

**Comment by olafdraeger** [comment]
No unfortunately no errors and without OptQuery it comes back with a full list of all videos.

**Comment by silentsokolov** [comment]
Please, try lowercase `videoName`

**Comment by olafdraeger** [comment]
no change. i'm trying this:
`videos, resp, err := client.Users.ListVideo("",  vimeo.OptQuery("gdpr article 20 eng"))`
the actual title fo the Video is: GDPR Article 20 ENG so the original query was more like this:
`videos, resp, err := client.Users.ListVideo("",  vimeo.OptQuery("GDPR Article 20 ENG"))`
Both, the original (upper case) and the lowercase strings yield the same result. Searching for it on the Viemo dashboard shows the matched video.

**Comment by olafdraeger** [comment]
I just opened the response and saw that I get a `500 Internal Server Error` from vimeo...

**Comment by silentsokolov** [comment]
I tried to find my videos. The search returned results if query only lowercase. I have no idea why the vimeo does not give the result ...

Try, `client.Users.ListVideo("", vimeo.OptQuery("gdpr"))` (without spaces)

**Comment by olafdraeger** [comment]
just got the following back from vimeo support:

> Can you try the same request with the query parameter weak_search=true?  Note that private videos are not indexed in search, and search is intended for finding videos public on vimeo.com. Weak search will use a legacy search service on our back end that will return private videos on your account based on your video names.

so i added it as an option:
`// OptWeakSearch is an optioan argument to an API call to allow useage of legacy search on the vimeo backend to find
// private videos
type OptWeakSearch bool

// Get return key/value for make query
func (o OptWeakSearch) Get() (string, string){
	return "weak_search", fmt.Sprint(o)
}`

and it indeed returned the private videos that I need to look up.

**Comment by silentsokolov** [comment]
Thanks @olafdraeger, I have [released](https://github.com/silentsokolov/go-vimeo/releases/tag/v2.2.2) a new version with bug fixes

**Comment by olafdraeger** [comment]
cool thanks @silentsokolov 
much appreciated!
