### ISSUE TITLE
resp.TotalPages might be incorrectly reporting total number of items, not pages

### ISSUE THREAD

**Issue by olafdraeger** [silentsokolov/go-vimeo#8]
after this call:
`videos, resp, err := client.Users.ListVideo("", vimeo.OptPerPage(100) )`

i can see that:
`resp.TotalPage = 1156`
but
`resp.LastPage = "/me/videos?per_page=100&page=12"`
so `TotalPages` should be _12_, not _1156_, correct?

**Comment by silentsokolov** [comment]
Yep, it bad name, `TotalPages` is total video objects.

Thx, fix it, you can use the `Total` in the next version
